version = 1

# TODO: Uncomment once the testz has been added.
# test_patterns = ["Tests/**"]

# TODO: Uncomment once the testz has been added.
# [[analyzers]]
# name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "csharp"
